//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactureDueNonPayee
    {
        public decimal IdFactureDueNonPaye { get; set; }
        public decimal IdVisite { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Montant { get; set; }
        public System.DateTime DateEcheance { get; set; }
        public decimal MontantEnAccompte { get; set; }
        public string Descriptif { get; set; }
    
        public virtual Visite Visite { get; set; }
    }
}
