//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class LieuStockage
    {
        public LieuStockage()
        {
            this.PieceConsommable = new HashSet<PieceConsommable>();
        }
    
        public decimal CodeLieuStockage { get; set; }
        public string Adresse { get; set; }
    
        public virtual ICollection<PieceConsommable> PieceConsommable { get; set; }
    }
}
