//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LignePiece
    {
        public decimal IdLigne { get; set; }
        [RegularExpression(@"^\d*$", ErrorMessage = "Doit être entier positif")]
        public decimal Prix { get; set; }
        [RegularExpression(@"^\d*$", ErrorMessage = "Doit être entier positif")]
        public decimal Quantite { get; set; }
        public decimal Code { get; set; }
    
        public virtual Ligne Ligne { get; set; }
        public virtual PieceConsommable PieceConsommable { get; set; }
    }
}
