//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne
    {
        public decimal IdLigne { get; set; }
        public decimal NumeroLigne { get; set; }
        public string TypeLigne { get; set; }
        public decimal IdDevis { get; set; }
    
        public virtual Devis Devis { get; set; }
        public virtual LigneCommentaire LigneCommentaire { get; set; }
        public virtual LigneOperation LigneOperation { get; set; }
        public virtual LignePiece LignePiece { get; set; }
    }
}
