//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marque
    {
        public Marque()
        {
            this.Concessionnaire = new HashSet<Concessionnaire>();
            this.Modele = new HashSet<Modele>();
        }
    
        public decimal IdMarque { get; set; }
        public string NomMarque { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual ICollection<Concessionnaire> Concessionnaire { get; set; }
        public virtual ICollection<Modele> Modele { get; set; }
    }
}
