//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationVisite
    {
        public decimal IdOperation { get; set; }
        public decimal IdVisite { get; set; }
        public decimal DureeEffective { get; set; }
        public decimal Prix { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Visite Visite { get; set; }
    }
}
