//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.LigneOperation = new HashSet<LigneOperation>();
            this.OperationVisite = new HashSet<OperationVisite>();
        }
    
        public decimal IdOperation { get; set; }
        public decimal CodeOperation { get; set; }
        public string Descriptif { get; set; }
        public decimal DureeHabituelle { get; set; }
        public decimal PrixUnitaire { get; set; }
        public decimal CodeOuvrier { get; set; }
    
        public virtual ICollection<LigneOperation> LigneOperation { get; set; }
        public virtual ICollection<OperationVisite> OperationVisite { get; set; }
        public virtual Ouvrier Ouvrier { get; set; }
    }
}
