//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionV
    {
        public OptionV()
        {
            this.Type = new HashSet<Type>();
            this.Vehicule = new HashSet<Vehicule>();
        }
    
        public decimal IdOption { get; set; }
        public decimal CodeOption { get; set; }
        public string NomOption { get; set; }
        public string Descriptif { get; set; }
        public decimal Prix { get; set; }
    
        public virtual ICollection<Type> Type { get; set; }
        public virtual ICollection<Vehicule> Vehicule { get; set; }
    }
}
