//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrier
    {
        public Ouvrier()
        {
            this.NumTelOuvrier = new HashSet<NumTelOuvrier>();
            this.Operation = new HashSet<Operation>();
        }
    
        public decimal CodeOuvrier { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime DateEntree { get; set; }
        public decimal IdQualification { get; set; }
    
        public virtual DegreQualification DegreQualification { get; set; }
        public virtual ICollection<NumTelOuvrier> NumTelOuvrier { get; set; }
        public virtual ICollection<Operation> Operation { get; set; }
    }
}
