//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PieceConsommable
    {
        public PieceConsommable()
        {
            this.LanguePiece = new HashSet<LanguePiece>();
            this.LignePiece = new HashSet<LignePiece>();
            this.ListePieceConsommable = new HashSet<ListePieceConsommable>();
        }
    
        public decimal Code { get; set; }
        public string Denomination { get; set; }
        public decimal PrixUnitaire { get; set; }
        public decimal QuantiteTheorique { get; set; }
        public System.DateTime DateDernierReleve { get; set; }
        public decimal QuantiteStockDernierReleve { get; set; }
        public string Consommable { get; set; }
        public decimal CodeLieuStockage { get; set; }
    
        public virtual ICollection<LanguePiece> LanguePiece { get; set; }
        public virtual LieuStockage LieuStockage { get; set; }
        public virtual ICollection<LignePiece> LignePiece { get; set; }
        public virtual ICollection<ListePieceConsommable> ListePieceConsommable { get; set; }
    }
}
