//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Possession
    {
        public Possession()
        {
            this.Devis = new HashSet<Devis>();
            this.Visite = new HashSet<Visite>();
        }
    
        public decimal IdPossession { get; set; }
        public decimal IdVehicule { get; set; }
        public string NumMineralogique { get; set; }
        public System.DateTime DateAchat { get; set; }
        public Nullable<System.DateTime> DateVendu { get; set; }
        public System.DateTime DateImmatriculation { get; set; }
        public decimal IdProprietaire { get; set; }
    
        public virtual ICollection<Devis> Devis { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
        public virtual Vehicule Vehicule { get; set; }
        public virtual ICollection<Visite> Visite { get; set; }
    }
}
