//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proprietaire
    {
        public Proprietaire()
        {
            this.NumTelProprio = new HashSet<NumTelProprio>();
            this.Possession = new HashSet<Possession>();
        }
    
        public decimal IdProprietaire { get; set; }
        public decimal NumRegNational { get; set; }
        public string NomProprio { get; set; }
        public string PrenomProprio { get; set; }
        public string Adresse { get; set; }
        public decimal CodeLangue { get; set; }
    
        public virtual Langue Langue { get; set; }
        public virtual ICollection<NumTelProprio> NumTelProprio { get; set; }
        public virtual ICollection<Possession> Possession { get; set; }
    }
}
