//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.Vehicule = new HashSet<Vehicule>();
            this.OptionV = new HashSet<OptionV>();
        }
    
        public decimal IdType { get; set; }
        public string NomTypeModele { get; set; }
        public decimal IdModele { get; set; }
        public string Cylindree { get; set; }
        public string Motorisation { get; set; }
    
        public virtual Modele Modele { get; set; }
        public virtual ICollection<Vehicule> Vehicule { get; set; }
        public virtual ICollection<OptionV> OptionV { get; set; }
    }
}
