//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarqueOpen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public Vehicule()
        {
            this.Possession = new HashSet<Possession>();
            this.OptionV = new HashSet<OptionV>();
        }
    
        public decimal IdVehicule { get; set; }
        public decimal NumChassis { get; set; }
        public decimal AnneeFabrication { get; set; }
        public string TypeVehicule { get; set; }
        public string ChargeMax { get; set; }
        public Nullable<System.DateTime> DateDernierControle { get; set; }
        public decimal IdType { get; set; }
        public decimal CodeJante { get; set; }
    
        public virtual Jante Jante { get; set; }
        public virtual ICollection<Possession> Possession { get; set; }
        public virtual Type Type { get; set; }
        public virtual ICollection<OptionV> OptionV { get; set; }
    }
}
